knpu_oauth2_client:
    clients:
        keycloak:
            type: keycloak
            client_id: '%env(OIDC_CLIENT_ID)%'
            client_secret: '%env(OIDC_CLIENT_SECRET)%'

            redirect_route: 'connect_keycloak_check'
            redirect_params: { }

            auth_server_url: '%env(OIDC_AUTH_SERVER_URL)%'

            realm: '%env(OIDC_REALM)%'
